LOCAL_PATH := $(call my-dir)

MY_CFLAGS := -std=c11 -Wno-unused-parameter
MY_CPPFLAGS := -std=c++11 -Wno-error=non-virtual-dtor
MY_C_INCLUDES := \
  $(LOCAL_PATH)/include \
  external/openssl/include \
  $(LOCAL_PATH)/third_party/protobuf/src \
  external/zlib


include $(CLEAR_VARS)
LOCAL_MODULE := libgpr

LOCAL_SRC_FILES := \
  src/core/lib/profiling/basic_timers.c \
  src/core/lib/profiling/stap_timers.c \
  src/core/lib/support/alloc.c \
  src/core/lib/support/avl.c \
  src/core/lib/support/backoff.c \
  src/core/lib/support/cmdline.c \
  src/core/lib/support/cpu_iphone.c \
  src/core/lib/support/cpu_linux.c \
  src/core/lib/support/cpu_posix.c \
  src/core/lib/support/cpu_windows.c \
  src/core/lib/support/env_linux.c \
  src/core/lib/support/env_posix.c \
  src/core/lib/support/env_windows.c \
  src/core/lib/support/histogram.c \
  src/core/lib/support/host_port.c \
  src/core/lib/support/log.c \
  src/core/lib/support/log_android.c \
  src/core/lib/support/log_linux.c \
  src/core/lib/support/log_posix.c \
  src/core/lib/support/log_windows.c \
  src/core/lib/support/murmur_hash.c \
  src/core/lib/support/slice.c \
  src/core/lib/support/slice_buffer.c \
  src/core/lib/support/stack_lockfree.c \
  src/core/lib/support/string.c \
  src/core/lib/support/string_posix.c \
  src/core/lib/support/string_util_windows.c \
  src/core/lib/support/string_windows.c \
  src/core/lib/support/subprocess_posix.c \
  src/core/lib/support/subprocess_windows.c \
  src/core/lib/support/sync.c \
  src/core/lib/support/sync_posix.c \
  src/core/lib/support/sync_windows.c \
  src/core/lib/support/thd.c \
  src/core/lib/support/thd_posix.c \
  src/core/lib/support/thd_windows.c \
  src/core/lib/support/time.c \
  src/core/lib/support/time_posix.c \
  src/core/lib/support/time_precise.c \
  src/core/lib/support/time_windows.c \
  src/core/lib/support/tls_pthread.c \
  src/core/lib/support/tmpfile_msys.c \
  src/core/lib/support/tmpfile_posix.c \
  src/core/lib/support/tmpfile_windows.c \
  src/core/lib/support/wrap_memcpy.c \

LOCAL_C_INCLUDES := $(MY_C_INCLUDES)
LOCAL_CFLAGS := $(MY_CFLAGS)
LOCAL_CPPFLAGS := $(MY_CPPFLAGS)

include $(BUILD_STATIC_LIBRARY)


include $(CLEAR_VARS)
LOCAL_MODULE := libgrpc

LOCAL_SRC_FILES := \
  src/core/lib/surface/init.c \
  src/core/lib/channel/channel_args.c \
  src/core/lib/channel/channel_stack.c \
  src/core/lib/channel/channel_stack_builder.c \
  src/core/lib/channel/compress_filter.c \
  src/core/lib/channel/connected_channel.c \
  src/core/lib/channel/http_client_filter.c \
  src/core/lib/channel/http_server_filter.c \
  src/core/lib/compression/compression.c \
  src/core/lib/compression/message_compress.c \
  src/core/lib/debug/trace.c \
  src/core/lib/http/format_request.c \
  src/core/lib/http/httpcli.c \
  src/core/lib/http/parser.c \
  src/core/lib/iomgr/closure.c \
  src/core/lib/iomgr/endpoint.c \
  src/core/lib/iomgr/endpoint_pair_posix.c \
  src/core/lib/iomgr/endpoint_pair_windows.c \
  src/core/lib/iomgr/error.c \
  src/core/lib/iomgr/ev_epoll_linux.c \
  src/core/lib/iomgr/ev_poll_and_epoll_posix.c \
  src/core/lib/iomgr/ev_poll_posix.c \
  src/core/lib/iomgr/ev_posix.c \
  src/core/lib/iomgr/exec_ctx.c \
  src/core/lib/iomgr/executor.c \
  src/core/lib/iomgr/iocp_windows.c \
  src/core/lib/iomgr/iomgr.c \
  src/core/lib/iomgr/iomgr_posix.c \
  src/core/lib/iomgr/iomgr_windows.c \
  src/core/lib/iomgr/load_file.c \
  src/core/lib/iomgr/network_status_tracker.c \
  src/core/lib/iomgr/polling_entity.c \
  src/core/lib/iomgr/pollset_set_windows.c \
  src/core/lib/iomgr/pollset_windows.c \
  src/core/lib/iomgr/resolve_address_posix.c \
  src/core/lib/iomgr/resolve_address_windows.c \
  src/core/lib/iomgr/sockaddr_utils.c \
  src/core/lib/iomgr/socket_utils_common_posix.c \
  src/core/lib/iomgr/socket_utils_linux.c \
  src/core/lib/iomgr/socket_utils_posix.c \
  src/core/lib/iomgr/socket_windows.c \
  src/core/lib/iomgr/tcp_client_posix.c \
  src/core/lib/iomgr/tcp_client_windows.c \
  src/core/lib/iomgr/tcp_posix.c \
  src/core/lib/iomgr/tcp_server_posix.c \
  src/core/lib/iomgr/tcp_server_windows.c \
  src/core/lib/iomgr/tcp_windows.c \
  src/core/lib/iomgr/time_averaged_stats.c \
  src/core/lib/iomgr/timer.c \
  src/core/lib/iomgr/timer_heap.c \
  src/core/lib/iomgr/udp_server.c \
  src/core/lib/iomgr/unix_sockets_posix.c \
  src/core/lib/iomgr/unix_sockets_posix_noop.c \
  src/core/lib/iomgr/wakeup_fd_eventfd.c \
  src/core/lib/iomgr/wakeup_fd_nospecial.c \
  src/core/lib/iomgr/wakeup_fd_pipe.c \
  src/core/lib/iomgr/wakeup_fd_posix.c \
  src/core/lib/iomgr/workqueue_posix.c \
  src/core/lib/iomgr/workqueue_windows.c \
  src/core/lib/json/json.c \
  src/core/lib/json/json_reader.c \
  src/core/lib/json/json_string.c \
  src/core/lib/json/json_writer.c \
  src/core/lib/surface/alarm.c \
  src/core/lib/surface/api_trace.c \
  src/core/lib/surface/byte_buffer.c \
  src/core/lib/surface/byte_buffer_reader.c \
  src/core/lib/surface/call.c \
  src/core/lib/surface/call_details.c \
  src/core/lib/surface/call_log_batch.c \
  src/core/lib/surface/channel.c \
  src/core/lib/surface/channel_init.c \
  src/core/lib/surface/channel_ping.c \
  src/core/lib/surface/channel_stack_type.c \
  src/core/lib/surface/completion_queue.c \
  src/core/lib/surface/event_string.c \
  src/core/lib/surface/lame_client.c \
  src/core/lib/surface/metadata_array.c \
  src/core/lib/surface/server.c \
  src/core/lib/surface/validate_metadata.c \
  src/core/lib/surface/version.c \
  src/core/lib/transport/byte_stream.c \
  src/core/lib/transport/connectivity_state.c \
  src/core/lib/transport/metadata.c \
  src/core/lib/transport/metadata_batch.c \
  src/core/lib/transport/static_metadata.c \
  src/core/lib/transport/transport.c \
  src/core/lib/transport/transport_op_string.c \
  src/core/ext/transport/chttp2/server/secure/server_secure_chttp2.c \
  src/core/ext/transport/chttp2/transport/bin_decoder.c \
  src/core/ext/transport/chttp2/transport/bin_encoder.c \
  src/core/ext/transport/chttp2/transport/chttp2_plugin.c \
  src/core/ext/transport/chttp2/transport/chttp2_transport.c \
  src/core/ext/transport/chttp2/transport/frame_data.c \
  src/core/ext/transport/chttp2/transport/frame_goaway.c \
  src/core/ext/transport/chttp2/transport/frame_ping.c \
  src/core/ext/transport/chttp2/transport/frame_rst_stream.c \
  src/core/ext/transport/chttp2/transport/frame_settings.c \
  src/core/ext/transport/chttp2/transport/frame_window_update.c \
  src/core/ext/transport/chttp2/transport/hpack_encoder.c \
  src/core/ext/transport/chttp2/transport/hpack_parser.c \
  src/core/ext/transport/chttp2/transport/hpack_table.c \
  src/core/ext/transport/chttp2/transport/huffsyms.c \
  src/core/ext/transport/chttp2/transport/incoming_metadata.c \
  src/core/ext/transport/chttp2/transport/parsing.c \
  src/core/ext/transport/chttp2/transport/status_conversion.c \
  src/core/ext/transport/chttp2/transport/stream_lists.c \
  src/core/ext/transport/chttp2/transport/stream_map.c \
  src/core/ext/transport/chttp2/transport/timeout_encoding.c \
  src/core/ext/transport/chttp2/transport/varint.c \
  src/core/ext/transport/chttp2/transport/writing.c \
  src/core/ext/transport/chttp2/alpn/alpn.c \
  src/core/lib/http/httpcli_security_connector.c \
  src/core/lib/security/context/security_context.c \
  src/core/lib/security/credentials/composite/composite_credentials.c \
  src/core/lib/security/credentials/credentials.c \
  src/core/lib/security/credentials/credentials_metadata.c \
  src/core/lib/security/credentials/fake/fake_credentials.c \
  src/core/lib/security/credentials/google_default/credentials_posix.c \
  src/core/lib/security/credentials/google_default/credentials_windows.c \
  src/core/lib/security/credentials/google_default/google_default_credentials.c \
  src/core/lib/security/credentials/iam/iam_credentials.c \
  src/core/lib/security/credentials/jwt/json_token.c \
  src/core/lib/security/credentials/jwt/jwt_credentials.c \
  src/core/lib/security/credentials/jwt/jwt_verifier.c \
  src/core/lib/security/credentials/oauth2/oauth2_credentials.c \
  src/core/lib/security/credentials/plugin/plugin_credentials.c \
  src/core/lib/security/credentials/ssl/ssl_credentials.c \
  src/core/lib/security/transport/client_auth_filter.c \
  src/core/lib/security/transport/handshake.c \
  src/core/lib/security/transport/secure_endpoint.c \
  src/core/lib/security/transport/security_connector.c \
  src/core/lib/security/transport/server_auth_filter.c \
  src/core/lib/security/transport/tsi_error.c \
  src/core/lib/security/util/b64.c \
  src/core/lib/security/util/json_util.c \
  src/core/lib/surface/init_secure.c \
  src/core/lib/tsi/fake_transport_security.c \
  src/core/lib/tsi/ssl_transport_security.c \
  src/core/lib/tsi/transport_security.c \
  src/core/ext/transport/chttp2/client/secure/secure_channel_create.c \
  src/core/ext/client_config/channel_connectivity.c \
  src/core/ext/client_config/client_channel.c \
  src/core/ext/client_config/client_channel_factory.c \
  src/core/ext/client_config/client_config.c \
  src/core/ext/client_config/client_config_plugin.c \
  src/core/ext/client_config/connector.c \
  src/core/ext/client_config/default_initial_connect_string.c \
  src/core/ext/client_config/initial_connect_string.c \
  src/core/ext/client_config/lb_policy.c \
  src/core/ext/client_config/lb_policy_factory.c \
  src/core/ext/client_config/lb_policy_registry.c \
  src/core/ext/client_config/parse_address.c \
  src/core/ext/client_config/resolver.c \
  src/core/ext/client_config/resolver_factory.c \
  src/core/ext/client_config/resolver_registry.c \
  src/core/ext/client_config/subchannel.c \
  src/core/ext/client_config/subchannel_call_holder.c \
  src/core/ext/client_config/subchannel_index.c \
  src/core/ext/client_config/uri_parser.c \
  src/core/ext/transport/chttp2/server/insecure/server_chttp2.c \
  src/core/ext/transport/chttp2/server/insecure/server_chttp2_posix.c \
  src/core/ext/transport/chttp2/client/insecure/channel_create.c \
  src/core/ext/transport/chttp2/client/insecure/channel_create_posix.c \
  src/core/ext/lb_policy/grpclb/load_balancer_api.c \
  src/core/ext/lb_policy/grpclb/proto/grpc/lb/v1/load_balancer.pb.c \
  third_party/nanopb/pb_common.c \
  third_party/nanopb/pb_decode.c \
  third_party/nanopb/pb_encode.c \
  src/core/ext/lb_policy/pick_first/pick_first.c \
  src/core/ext/lb_policy/round_robin/round_robin.c \
  src/core/ext/resolver/dns/native/dns_resolver.c \
  src/core/ext/resolver/sockaddr/sockaddr_resolver.c \
  src/core/ext/load_reporting/load_reporting.c \
  src/core/ext/load_reporting/load_reporting_filter.c \
  src/core/ext/census/context.c \
  src/core/ext/census/gen/census.pb.c \
  src/core/ext/census/grpc_context.c \
  src/core/ext/census/grpc_filter.c \
  src/core/ext/census/grpc_plugin.c \
  src/core/ext/census/initialize.c \
  src/core/ext/census/mlog.c \
  src/core/ext/census/operation.c \
  src/core/ext/census/placeholders.c \
  src/core/ext/census/tracing.c \
  src/core/plugin_registry/grpc_plugin_registry.c \

LOCAL_C_INCLUDES := $(MY_C_INCLUDES)
LOCAL_CFLAGS := $(MY_CFLAGS)
LOCAL_CPPFLAGS := $(MY_CPPFLAGS)
LOCAL_STATIC_LIBRARIES := libssl_static libz libgpr

include $(BUILD_STATIC_LIBRARY)


include $(CLEAR_VARS)
LOCAL_MODULE := libgrpc_cronet

LOCAL_SRC_FILES := \
  src/core/lib/surface/init.c \
  src/core/lib/channel/channel_args.c \
  src/core/lib/channel/channel_stack.c \
  src/core/lib/channel/channel_stack_builder.c \
  src/core/lib/channel/compress_filter.c \
  src/core/lib/channel/connected_channel.c \
  src/core/lib/channel/http_client_filter.c \
  src/core/lib/channel/http_server_filter.c \
  src/core/lib/compression/compression.c \
  src/core/lib/compression/message_compress.c \
  src/core/lib/debug/trace.c \
  src/core/lib/http/format_request.c \
  src/core/lib/http/httpcli.c \
  src/core/lib/http/parser.c \
  src/core/lib/iomgr/closure.c \
  src/core/lib/iomgr/endpoint.c \
  src/core/lib/iomgr/endpoint_pair_posix.c \
  src/core/lib/iomgr/endpoint_pair_windows.c \
  src/core/lib/iomgr/error.c \
  src/core/lib/iomgr/ev_epoll_linux.c \
  src/core/lib/iomgr/ev_poll_and_epoll_posix.c \
  src/core/lib/iomgr/ev_poll_posix.c \
  src/core/lib/iomgr/ev_posix.c \
  src/core/lib/iomgr/exec_ctx.c \
  src/core/lib/iomgr/executor.c \
  src/core/lib/iomgr/iocp_windows.c \
  src/core/lib/iomgr/iomgr.c \
  src/core/lib/iomgr/iomgr_posix.c \
  src/core/lib/iomgr/iomgr_windows.c \
  src/core/lib/iomgr/load_file.c \
  src/core/lib/iomgr/network_status_tracker.c \
  src/core/lib/iomgr/polling_entity.c \
  src/core/lib/iomgr/pollset_set_windows.c \
  src/core/lib/iomgr/pollset_windows.c \
  src/core/lib/iomgr/resolve_address_posix.c \
  src/core/lib/iomgr/resolve_address_windows.c \
  src/core/lib/iomgr/sockaddr_utils.c \
  src/core/lib/iomgr/socket_utils_common_posix.c \
  src/core/lib/iomgr/socket_utils_linux.c \
  src/core/lib/iomgr/socket_utils_posix.c \
  src/core/lib/iomgr/socket_windows.c \
  src/core/lib/iomgr/tcp_client_posix.c \
  src/core/lib/iomgr/tcp_client_windows.c \
  src/core/lib/iomgr/tcp_posix.c \
  src/core/lib/iomgr/tcp_server_posix.c \
  src/core/lib/iomgr/tcp_server_windows.c \
  src/core/lib/iomgr/tcp_windows.c \
  src/core/lib/iomgr/time_averaged_stats.c \
  src/core/lib/iomgr/timer.c \
  src/core/lib/iomgr/timer_heap.c \
  src/core/lib/iomgr/udp_server.c \
  src/core/lib/iomgr/unix_sockets_posix.c \
  src/core/lib/iomgr/unix_sockets_posix_noop.c \
  src/core/lib/iomgr/wakeup_fd_eventfd.c \
  src/core/lib/iomgr/wakeup_fd_nospecial.c \
  src/core/lib/iomgr/wakeup_fd_pipe.c \
  src/core/lib/iomgr/wakeup_fd_posix.c \
  src/core/lib/iomgr/workqueue_posix.c \
  src/core/lib/iomgr/workqueue_windows.c \
  src/core/lib/json/json.c \
  src/core/lib/json/json_reader.c \
  src/core/lib/json/json_string.c \
  src/core/lib/json/json_writer.c \
  src/core/lib/surface/alarm.c \
  src/core/lib/surface/api_trace.c \
  src/core/lib/surface/byte_buffer.c \
  src/core/lib/surface/byte_buffer_reader.c \
  src/core/lib/surface/call.c \
  src/core/lib/surface/call_details.c \
  src/core/lib/surface/call_log_batch.c \
  src/core/lib/surface/channel.c \
  src/core/lib/surface/channel_init.c \
  src/core/lib/surface/channel_ping.c \
  src/core/lib/surface/channel_stack_type.c \
  src/core/lib/surface/completion_queue.c \
  src/core/lib/surface/event_string.c \
  src/core/lib/surface/lame_client.c \
  src/core/lib/surface/metadata_array.c \
  src/core/lib/surface/server.c \
  src/core/lib/surface/validate_metadata.c \
  src/core/lib/surface/version.c \
  src/core/lib/transport/byte_stream.c \
  src/core/lib/transport/connectivity_state.c \
  src/core/lib/transport/metadata.c \
  src/core/lib/transport/metadata_batch.c \
  src/core/lib/transport/static_metadata.c \
  src/core/lib/transport/transport.c \
  src/core/lib/transport/transport_op_string.c \
  src/core/ext/transport/cronet/client/secure/cronet_channel_create.c \
  src/core/ext/transport/cronet/transport/cronet_api_dummy.c \
  src/core/ext/transport/cronet/transport/cronet_transport.c \
  src/core/ext/transport/chttp2/client/secure/secure_channel_create.c \
  src/core/ext/transport/chttp2/transport/bin_decoder.c \
  src/core/ext/transport/chttp2/transport/bin_encoder.c \
  src/core/ext/transport/chttp2/transport/chttp2_plugin.c \
  src/core/ext/transport/chttp2/transport/chttp2_transport.c \
  src/core/ext/transport/chttp2/transport/frame_data.c \
  src/core/ext/transport/chttp2/transport/frame_goaway.c \
  src/core/ext/transport/chttp2/transport/frame_ping.c \
  src/core/ext/transport/chttp2/transport/frame_rst_stream.c \
  src/core/ext/transport/chttp2/transport/frame_settings.c \
  src/core/ext/transport/chttp2/transport/frame_window_update.c \
  src/core/ext/transport/chttp2/transport/hpack_encoder.c \
  src/core/ext/transport/chttp2/transport/hpack_parser.c \
  src/core/ext/transport/chttp2/transport/hpack_table.c \
  src/core/ext/transport/chttp2/transport/huffsyms.c \
  src/core/ext/transport/chttp2/transport/incoming_metadata.c \
  src/core/ext/transport/chttp2/transport/parsing.c \
  src/core/ext/transport/chttp2/transport/status_conversion.c \
  src/core/ext/transport/chttp2/transport/stream_lists.c \
  src/core/ext/transport/chttp2/transport/stream_map.c \
  src/core/ext/transport/chttp2/transport/timeout_encoding.c \
  src/core/ext/transport/chttp2/transport/varint.c \
  src/core/ext/transport/chttp2/transport/writing.c \
  src/core/ext/transport/chttp2/alpn/alpn.c \
  src/core/ext/client_config/channel_connectivity.c \
  src/core/ext/client_config/client_channel.c \
  src/core/ext/client_config/client_channel_factory.c \
  src/core/ext/client_config/client_config.c \
  src/core/ext/client_config/client_config_plugin.c \
  src/core/ext/client_config/connector.c \
  src/core/ext/client_config/default_initial_connect_string.c \
  src/core/ext/client_config/initial_connect_string.c \
  src/core/ext/client_config/lb_policy.c \
  src/core/ext/client_config/lb_policy_factory.c \
  src/core/ext/client_config/lb_policy_registry.c \
  src/core/ext/client_config/parse_address.c \
  src/core/ext/client_config/resolver.c \
  src/core/ext/client_config/resolver_factory.c \
  src/core/ext/client_config/resolver_registry.c \
  src/core/ext/client_config/subchannel.c \
  src/core/ext/client_config/subchannel_call_holder.c \
  src/core/ext/client_config/subchannel_index.c \
  src/core/ext/client_config/uri_parser.c \
  src/core/lib/http/httpcli_security_connector.c \
  src/core/lib/security/context/security_context.c \
  src/core/lib/security/credentials/composite/composite_credentials.c \
  src/core/lib/security/credentials/credentials.c \
  src/core/lib/security/credentials/credentials_metadata.c \
  src/core/lib/security/credentials/fake/fake_credentials.c \
  src/core/lib/security/credentials/google_default/credentials_posix.c \
  src/core/lib/security/credentials/google_default/credentials_windows.c \
  src/core/lib/security/credentials/google_default/google_default_credentials.c \
  src/core/lib/security/credentials/iam/iam_credentials.c \
  src/core/lib/security/credentials/jwt/json_token.c \
  src/core/lib/security/credentials/jwt/jwt_credentials.c \
  src/core/lib/security/credentials/jwt/jwt_verifier.c \
  src/core/lib/security/credentials/oauth2/oauth2_credentials.c \
  src/core/lib/security/credentials/plugin/plugin_credentials.c \
  src/core/lib/security/credentials/ssl/ssl_credentials.c \
  src/core/lib/security/transport/client_auth_filter.c \
  src/core/lib/security/transport/handshake.c \
  src/core/lib/security/transport/secure_endpoint.c \
  src/core/lib/security/transport/security_connector.c \
  src/core/lib/security/transport/server_auth_filter.c \
  src/core/lib/security/transport/tsi_error.c \
  src/core/lib/security/util/b64.c \
  src/core/lib/security/util/json_util.c \
  src/core/lib/surface/init_secure.c \
  src/core/lib/tsi/fake_transport_security.c \
  src/core/lib/tsi/ssl_transport_security.c \
  src/core/lib/tsi/transport_security.c \
  src/core/plugin_registry/grpc_cronet_plugin_registry.c \

LOCAL_C_INCLUDES := $(MY_C_INCLUDES)
LOCAL_CFLAGS := $(MY_CFLAGS)
LOCAL_CPPFLAGS := $(MY_CPPFLAGS)
LOCAL_STATIC_LIBRARIES := libssl_static libgpr

include $(BUILD_STATIC_LIBRARY)


include $(CLEAR_VARS)
LOCAL_MODULE := libgrpc_unsecure

LOCAL_SRC_FILES := \
  src/core/lib/surface/init.c \
  src/core/lib/surface/init_unsecure.c \
  src/core/lib/channel/channel_args.c \
  src/core/lib/channel/channel_stack.c \
  src/core/lib/channel/channel_stack_builder.c \
  src/core/lib/channel/compress_filter.c \
  src/core/lib/channel/connected_channel.c \
  src/core/lib/channel/http_client_filter.c \
  src/core/lib/channel/http_server_filter.c \
  src/core/lib/compression/compression.c \
  src/core/lib/compression/message_compress.c \
  src/core/lib/debug/trace.c \
  src/core/lib/http/format_request.c \
  src/core/lib/http/httpcli.c \
  src/core/lib/http/parser.c \
  src/core/lib/iomgr/closure.c \
  src/core/lib/iomgr/endpoint.c \
  src/core/lib/iomgr/endpoint_pair_posix.c \
  src/core/lib/iomgr/endpoint_pair_windows.c \
  src/core/lib/iomgr/error.c \
  src/core/lib/iomgr/ev_epoll_linux.c \
  src/core/lib/iomgr/ev_poll_and_epoll_posix.c \
  src/core/lib/iomgr/ev_poll_posix.c \
  src/core/lib/iomgr/ev_posix.c \
  src/core/lib/iomgr/exec_ctx.c \
  src/core/lib/iomgr/executor.c \
  src/core/lib/iomgr/iocp_windows.c \
  src/core/lib/iomgr/iomgr.c \
  src/core/lib/iomgr/iomgr_posix.c \
  src/core/lib/iomgr/iomgr_windows.c \
  src/core/lib/iomgr/load_file.c \
  src/core/lib/iomgr/network_status_tracker.c \
  src/core/lib/iomgr/polling_entity.c \
  src/core/lib/iomgr/pollset_set_windows.c \
  src/core/lib/iomgr/pollset_windows.c \
  src/core/lib/iomgr/resolve_address_posix.c \
  src/core/lib/iomgr/resolve_address_windows.c \
  src/core/lib/iomgr/sockaddr_utils.c \
  src/core/lib/iomgr/socket_utils_common_posix.c \
  src/core/lib/iomgr/socket_utils_linux.c \
  src/core/lib/iomgr/socket_utils_posix.c \
  src/core/lib/iomgr/socket_windows.c \
  src/core/lib/iomgr/tcp_client_posix.c \
  src/core/lib/iomgr/tcp_client_windows.c \
  src/core/lib/iomgr/tcp_posix.c \
  src/core/lib/iomgr/tcp_server_posix.c \
  src/core/lib/iomgr/tcp_server_windows.c \
  src/core/lib/iomgr/tcp_windows.c \
  src/core/lib/iomgr/time_averaged_stats.c \
  src/core/lib/iomgr/timer.c \
  src/core/lib/iomgr/timer_heap.c \
  src/core/lib/iomgr/udp_server.c \
  src/core/lib/iomgr/unix_sockets_posix.c \
  src/core/lib/iomgr/unix_sockets_posix_noop.c \
  src/core/lib/iomgr/wakeup_fd_eventfd.c \
  src/core/lib/iomgr/wakeup_fd_nospecial.c \
  src/core/lib/iomgr/wakeup_fd_pipe.c \
  src/core/lib/iomgr/wakeup_fd_posix.c \
  src/core/lib/iomgr/workqueue_posix.c \
  src/core/lib/iomgr/workqueue_windows.c \
  src/core/lib/json/json.c \
  src/core/lib/json/json_reader.c \
  src/core/lib/json/json_string.c \
  src/core/lib/json/json_writer.c \
  src/core/lib/surface/alarm.c \
  src/core/lib/surface/api_trace.c \
  src/core/lib/surface/byte_buffer.c \
  src/core/lib/surface/byte_buffer_reader.c \
  src/core/lib/surface/call.c \
  src/core/lib/surface/call_details.c \
  src/core/lib/surface/call_log_batch.c \
  src/core/lib/surface/channel.c \
  src/core/lib/surface/channel_init.c \
  src/core/lib/surface/channel_ping.c \
  src/core/lib/surface/channel_stack_type.c \
  src/core/lib/surface/completion_queue.c \
  src/core/lib/surface/event_string.c \
  src/core/lib/surface/lame_client.c \
  src/core/lib/surface/metadata_array.c \
  src/core/lib/surface/server.c \
  src/core/lib/surface/validate_metadata.c \
  src/core/lib/surface/version.c \
  src/core/lib/transport/byte_stream.c \
  src/core/lib/transport/connectivity_state.c \
  src/core/lib/transport/metadata.c \
  src/core/lib/transport/metadata_batch.c \
  src/core/lib/transport/static_metadata.c \
  src/core/lib/transport/transport.c \
  src/core/lib/transport/transport_op_string.c \
  src/core/ext/transport/chttp2/server/insecure/server_chttp2.c \
  src/core/ext/transport/chttp2/server/insecure/server_chttp2_posix.c \
  src/core/ext/transport/chttp2/transport/bin_decoder.c \
  src/core/ext/transport/chttp2/transport/bin_encoder.c \
  src/core/ext/transport/chttp2/transport/chttp2_plugin.c \
  src/core/ext/transport/chttp2/transport/chttp2_transport.c \
  src/core/ext/transport/chttp2/transport/frame_data.c \
  src/core/ext/transport/chttp2/transport/frame_goaway.c \
  src/core/ext/transport/chttp2/transport/frame_ping.c \
  src/core/ext/transport/chttp2/transport/frame_rst_stream.c \
  src/core/ext/transport/chttp2/transport/frame_settings.c \
  src/core/ext/transport/chttp2/transport/frame_window_update.c \
  src/core/ext/transport/chttp2/transport/hpack_encoder.c \
  src/core/ext/transport/chttp2/transport/hpack_parser.c \
  src/core/ext/transport/chttp2/transport/hpack_table.c \
  src/core/ext/transport/chttp2/transport/huffsyms.c \
  src/core/ext/transport/chttp2/transport/incoming_metadata.c \
  src/core/ext/transport/chttp2/transport/parsing.c \
  src/core/ext/transport/chttp2/transport/status_conversion.c \
  src/core/ext/transport/chttp2/transport/stream_lists.c \
  src/core/ext/transport/chttp2/transport/stream_map.c \
  src/core/ext/transport/chttp2/transport/timeout_encoding.c \
  src/core/ext/transport/chttp2/transport/varint.c \
  src/core/ext/transport/chttp2/transport/writing.c \
  src/core/ext/transport/chttp2/alpn/alpn.c \
  src/core/ext/transport/chttp2/client/insecure/channel_create.c \
  src/core/ext/transport/chttp2/client/insecure/channel_create_posix.c \
  src/core/ext/client_config/channel_connectivity.c \
  src/core/ext/client_config/client_channel.c \
  src/core/ext/client_config/client_channel_factory.c \
  src/core/ext/client_config/client_config.c \
  src/core/ext/client_config/client_config_plugin.c \
  src/core/ext/client_config/connector.c \
  src/core/ext/client_config/default_initial_connect_string.c \
  src/core/ext/client_config/initial_connect_string.c \
  src/core/ext/client_config/lb_policy.c \
  src/core/ext/client_config/lb_policy_factory.c \
  src/core/ext/client_config/lb_policy_registry.c \
  src/core/ext/client_config/parse_address.c \
  src/core/ext/client_config/resolver.c \
  src/core/ext/client_config/resolver_factory.c \
  src/core/ext/client_config/resolver_registry.c \
  src/core/ext/client_config/subchannel.c \
  src/core/ext/client_config/subchannel_call_holder.c \
  src/core/ext/client_config/subchannel_index.c \
  src/core/ext/client_config/uri_parser.c \
  src/core/ext/resolver/dns/native/dns_resolver.c \
  src/core/ext/resolver/sockaddr/sockaddr_resolver.c \
  src/core/ext/load_reporting/load_reporting.c \
  src/core/ext/load_reporting/load_reporting_filter.c \
  src/core/ext/lb_policy/grpclb/load_balancer_api.c \
  src/core/ext/lb_policy/grpclb/proto/grpc/lb/v1/load_balancer.pb.c \
  third_party/nanopb/pb_common.c \
  third_party/nanopb/pb_decode.c \
  third_party/nanopb/pb_encode.c \
  src/core/ext/lb_policy/pick_first/pick_first.c \
  src/core/ext/lb_policy/round_robin/round_robin.c \
  src/core/ext/census/context.c \
  src/core/ext/census/gen/census.pb.c \
  src/core/ext/census/grpc_context.c \
  src/core/ext/census/grpc_filter.c \
  src/core/ext/census/grpc_plugin.c \
  src/core/ext/census/initialize.c \
  src/core/ext/census/mlog.c \
  src/core/ext/census/operation.c \
  src/core/ext/census/placeholders.c \
  src/core/ext/census/tracing.c \
  src/core/plugin_registry/grpc_unsecure_plugin_registry.c \

LOCAL_C_INCLUDES := $(MY_C_INCLUDES)
LOCAL_CFLAGS := $(MY_CFLAGS)
LOCAL_CPPFLAGS := $(MY_CPPFLAGS)
LOCAL_STATIC_LIBRARIES := libgpr

include $(BUILD_STATIC_LIBRARY)


include $(CLEAR_VARS)
LOCAL_MODULE := libgrpc++

LOCAL_CPP_EXTENSION := cc
LOCAL_SRC_FILES := \
  src/cpp/client/secure_credentials.cc \
  src/cpp/common/auth_property_iterator.cc \
  src/cpp/common/secure_auth_context.cc \
  src/cpp/common/secure_channel_arguments.cc \
  src/cpp/common/secure_create_auth_context.cc \
  src/cpp/server/secure_server_credentials.cc \
  src/cpp/client/channel.cc \
  src/cpp/client/client_context.cc \
  src/cpp/client/create_channel.cc \
  src/cpp/client/create_channel_internal.cc \
  src/cpp/client/create_channel_posix.cc \
  src/cpp/client/credentials.cc \
  src/cpp/client/generic_stub.cc \
  src/cpp/client/insecure_credentials.cc \
  src/cpp/common/channel_arguments.cc \
  src/cpp/common/completion_queue.cc \
  src/cpp/common/core_codegen.cc \
  src/cpp/common/rpc_method.cc \
  src/cpp/server/async_generic_service.cc \
  src/cpp/server/create_default_thread_pool.cc \
  src/cpp/server/dynamic_thread_pool.cc \
  src/cpp/server/insecure_server_credentials.cc \
  src/cpp/server/server.cc \
  src/cpp/server/server_builder.cc \
  src/cpp/server/server_context.cc \
  src/cpp/server/server_credentials.cc \
  src/cpp/server/server_posix.cc \
  src/cpp/util/byte_buffer.cc \
  src/cpp/util/slice.cc \
  src/cpp/util/status.cc \
  src/cpp/util/string_ref.cc \
  src/cpp/util/time.cc \
  src/core/lib/channel/channel_args.c \
  src/core/lib/channel/channel_stack.c \
  src/core/lib/channel/channel_stack_builder.c \
  src/core/lib/channel/compress_filter.c \
  src/core/lib/channel/connected_channel.c \
  src/core/lib/channel/http_client_filter.c \
  src/core/lib/channel/http_server_filter.c \
  src/core/lib/compression/compression.c \
  src/core/lib/compression/message_compress.c \
  src/core/lib/debug/trace.c \
  src/core/lib/http/format_request.c \
  src/core/lib/http/httpcli.c \
  src/core/lib/http/parser.c \
  src/core/lib/iomgr/closure.c \
  src/core/lib/iomgr/endpoint.c \
  src/core/lib/iomgr/endpoint_pair_posix.c \
  src/core/lib/iomgr/endpoint_pair_windows.c \
  src/core/lib/iomgr/error.c \
  src/core/lib/iomgr/ev_epoll_linux.c \
  src/core/lib/iomgr/ev_poll_and_epoll_posix.c \
  src/core/lib/iomgr/ev_poll_posix.c \
  src/core/lib/iomgr/ev_posix.c \
  src/core/lib/iomgr/exec_ctx.c \
  src/core/lib/iomgr/executor.c \
  src/core/lib/iomgr/iocp_windows.c \
  src/core/lib/iomgr/iomgr.c \
  src/core/lib/iomgr/iomgr_posix.c \
  src/core/lib/iomgr/iomgr_windows.c \
  src/core/lib/iomgr/load_file.c \
  src/core/lib/iomgr/network_status_tracker.c \
  src/core/lib/iomgr/polling_entity.c \
  src/core/lib/iomgr/pollset_set_windows.c \
  src/core/lib/iomgr/pollset_windows.c \
  src/core/lib/iomgr/resolve_address_posix.c \
  src/core/lib/iomgr/resolve_address_windows.c \
  src/core/lib/iomgr/sockaddr_utils.c \
  src/core/lib/iomgr/socket_utils_common_posix.c \
  src/core/lib/iomgr/socket_utils_linux.c \
  src/core/lib/iomgr/socket_utils_posix.c \
  src/core/lib/iomgr/socket_windows.c \
  src/core/lib/iomgr/tcp_client_posix.c \
  src/core/lib/iomgr/tcp_client_windows.c \
  src/core/lib/iomgr/tcp_posix.c \
  src/core/lib/iomgr/tcp_server_posix.c \
  src/core/lib/iomgr/tcp_server_windows.c \
  src/core/lib/iomgr/tcp_windows.c \
  src/core/lib/iomgr/time_averaged_stats.c \
  src/core/lib/iomgr/timer.c \
  src/core/lib/iomgr/timer_heap.c \
  src/core/lib/iomgr/udp_server.c \
  src/core/lib/iomgr/unix_sockets_posix.c \
  src/core/lib/iomgr/unix_sockets_posix_noop.c \
  src/core/lib/iomgr/wakeup_fd_eventfd.c \
  src/core/lib/iomgr/wakeup_fd_nospecial.c \
  src/core/lib/iomgr/wakeup_fd_pipe.c \
  src/core/lib/iomgr/wakeup_fd_posix.c \
  src/core/lib/iomgr/workqueue_posix.c \
  src/core/lib/iomgr/workqueue_windows.c \
  src/core/lib/json/json.c \
  src/core/lib/json/json_reader.c \
  src/core/lib/json/json_string.c \
  src/core/lib/json/json_writer.c \
  src/core/lib/surface/alarm.c \
  src/core/lib/surface/api_trace.c \
  src/core/lib/surface/byte_buffer.c \
  src/core/lib/surface/byte_buffer_reader.c \
  src/core/lib/surface/call.c \
  src/core/lib/surface/call_details.c \
  src/core/lib/surface/call_log_batch.c \
  src/core/lib/surface/channel.c \
  src/core/lib/surface/channel_init.c \
  src/core/lib/surface/channel_ping.c \
  src/core/lib/surface/channel_stack_type.c \
  src/core/lib/surface/completion_queue.c \
  src/core/lib/surface/event_string.c \
  src/core/lib/surface/lame_client.c \
  src/core/lib/surface/metadata_array.c \
  src/core/lib/surface/server.c \
  src/core/lib/surface/validate_metadata.c \
  src/core/lib/surface/version.c \
  src/core/lib/transport/byte_stream.c \
  src/core/lib/transport/connectivity_state.c \
  src/core/lib/transport/metadata.c \
  src/core/lib/transport/metadata_batch.c \
  src/core/lib/transport/static_metadata.c \
  src/core/lib/transport/transport.c \
  src/core/lib/transport/transport_op_string.c \
  src/cpp/codegen/codegen_init.cc \

LOCAL_C_INCLUDES := $(MY_C_INCLUDES)
LOCAL_CFLAGS := $(MY_CFLAGS)
LOCAL_CPPFLAGS := $(MY_CPPFLAGS)
LOCAL_STATIC_LIBRARIES := libssl_static libprotobuf libgrpc libgpr
include external/libcxx/libcxx.mk

include $(BUILD_STATIC_LIBRARY)


include $(CLEAR_VARS)
LOCAL_MODULE := libgrpc++_reflection

LOCAL_CPP_EXTENSION := cc
LOCAL_SRC_FILES := \
  src/cpp/ext/proto_server_reflection.cc \
  src/cpp/ext/proto_server_reflection_plugin.cc \
  src/cpp/ext/reflection.grpc.pb.cc \
  src/cpp/ext/reflection.pb.cc \

LOCAL_C_INCLUDES := $(MY_C_INCLUDES)
LOCAL_CFLAGS := $(MY_CFLAGS)
LOCAL_CPPFLAGS := $(MY_CPPFLAGS) -frtti
LOCAL_STATIC_LIBRARIES := libgrpc++
include external/libcxx/libcxx.mk

include $(BUILD_STATIC_LIBRARY)


include $(CLEAR_VARS)
LOCAL_MODULE := libgrpc++_unsecure

LOCAL_CPP_EXTENSION := cc
LOCAL_SRC_FILES := \
  src/cpp/common/insecure_create_auth_context.cc \
  src/cpp/client/channel.cc \
  src/cpp/client/client_context.cc \
  src/cpp/client/create_channel.cc \
  src/cpp/client/create_channel_internal.cc \
  src/cpp/client/create_channel_posix.cc \
  src/cpp/client/credentials.cc \
  src/cpp/client/generic_stub.cc \
  src/cpp/client/insecure_credentials.cc \
  src/cpp/common/channel_arguments.cc \
  src/cpp/common/completion_queue.cc \
  src/cpp/common/core_codegen.cc \
  src/cpp/common/rpc_method.cc \
  src/cpp/server/async_generic_service.cc \
  src/cpp/server/create_default_thread_pool.cc \
  src/cpp/server/dynamic_thread_pool.cc \
  src/cpp/server/insecure_server_credentials.cc \
  src/cpp/server/server.cc \
  src/cpp/server/server_builder.cc \
  src/cpp/server/server_context.cc \
  src/cpp/server/server_credentials.cc \
  src/cpp/server/server_posix.cc \
  src/cpp/util/byte_buffer.cc \
  src/cpp/util/slice.cc \
  src/cpp/util/status.cc \
  src/cpp/util/string_ref.cc \
  src/cpp/util/time.cc \
  src/core/lib/channel/channel_args.c \
  src/core/lib/channel/channel_stack.c \
  src/core/lib/channel/channel_stack_builder.c \
  src/core/lib/channel/compress_filter.c \
  src/core/lib/channel/connected_channel.c \
  src/core/lib/channel/http_client_filter.c \
  src/core/lib/channel/http_server_filter.c \
  src/core/lib/compression/compression.c \
  src/core/lib/compression/message_compress.c \
  src/core/lib/debug/trace.c \
  src/core/lib/http/format_request.c \
  src/core/lib/http/httpcli.c \
  src/core/lib/http/parser.c \
  src/core/lib/iomgr/closure.c \
  src/core/lib/iomgr/endpoint.c \
  src/core/lib/iomgr/endpoint_pair_posix.c \
  src/core/lib/iomgr/endpoint_pair_windows.c \
  src/core/lib/iomgr/error.c \
  src/core/lib/iomgr/ev_epoll_linux.c \
  src/core/lib/iomgr/ev_poll_and_epoll_posix.c \
  src/core/lib/iomgr/ev_poll_posix.c \
  src/core/lib/iomgr/ev_posix.c \
  src/core/lib/iomgr/exec_ctx.c \
  src/core/lib/iomgr/executor.c \
  src/core/lib/iomgr/iocp_windows.c \
  src/core/lib/iomgr/iomgr.c \
  src/core/lib/iomgr/iomgr_posix.c \
  src/core/lib/iomgr/iomgr_windows.c \
  src/core/lib/iomgr/load_file.c \
  src/core/lib/iomgr/network_status_tracker.c \
  src/core/lib/iomgr/polling_entity.c \
  src/core/lib/iomgr/pollset_set_windows.c \
  src/core/lib/iomgr/pollset_windows.c \
  src/core/lib/iomgr/resolve_address_posix.c \
  src/core/lib/iomgr/resolve_address_windows.c \
  src/core/lib/iomgr/sockaddr_utils.c \
  src/core/lib/iomgr/socket_utils_common_posix.c \
  src/core/lib/iomgr/socket_utils_linux.c \
  src/core/lib/iomgr/socket_utils_posix.c \
  src/core/lib/iomgr/socket_windows.c \
  src/core/lib/iomgr/tcp_client_posix.c \
  src/core/lib/iomgr/tcp_client_windows.c \
  src/core/lib/iomgr/tcp_posix.c \
  src/core/lib/iomgr/tcp_server_posix.c \
  src/core/lib/iomgr/tcp_server_windows.c \
  src/core/lib/iomgr/tcp_windows.c \
  src/core/lib/iomgr/time_averaged_stats.c \
  src/core/lib/iomgr/timer.c \
  src/core/lib/iomgr/timer_heap.c \
  src/core/lib/iomgr/udp_server.c \
  src/core/lib/iomgr/unix_sockets_posix.c \
  src/core/lib/iomgr/unix_sockets_posix_noop.c \
  src/core/lib/iomgr/wakeup_fd_eventfd.c \
  src/core/lib/iomgr/wakeup_fd_nospecial.c \
  src/core/lib/iomgr/wakeup_fd_pipe.c \
  src/core/lib/iomgr/wakeup_fd_posix.c \
  src/core/lib/iomgr/workqueue_posix.c \
  src/core/lib/iomgr/workqueue_windows.c \
  src/core/lib/json/json.c \
  src/core/lib/json/json_reader.c \
  src/core/lib/json/json_string.c \
  src/core/lib/json/json_writer.c \
  src/core/lib/surface/alarm.c \
  src/core/lib/surface/api_trace.c \
  src/core/lib/surface/byte_buffer.c \
  src/core/lib/surface/byte_buffer_reader.c \
  src/core/lib/surface/call.c \
  src/core/lib/surface/call_details.c \
  src/core/lib/surface/call_log_batch.c \
  src/core/lib/surface/channel.c \
  src/core/lib/surface/channel_init.c \
  src/core/lib/surface/channel_ping.c \
  src/core/lib/surface/channel_stack_type.c \
  src/core/lib/surface/completion_queue.c \
  src/core/lib/surface/event_string.c \
  src/core/lib/surface/lame_client.c \
  src/core/lib/surface/metadata_array.c \
  src/core/lib/surface/server.c \
  src/core/lib/surface/validate_metadata.c \
  src/core/lib/surface/version.c \
  src/core/lib/transport/byte_stream.c \
  src/core/lib/transport/connectivity_state.c \
  src/core/lib/transport/metadata.c \
  src/core/lib/transport/metadata_batch.c \
  src/core/lib/transport/static_metadata.c \
  src/core/lib/transport/transport.c \
  src/core/lib/transport/transport_op_string.c \
  src/cpp/codegen/codegen_init.cc \

LOCAL_C_INCLUDES := $(MY_C_INCLUDES)
LOCAL_CFLAGS := $(MY_CFLAGS)
LOCAL_CPPFLAGS := $(MY_CPPFLAGS)
LOCAL_STATIC_LIBRARIES := libprotobuf libgpr libgrpc_unsecure
include external/libcxx/libcxx.mk

include $(BUILD_STATIC_LIBRARY)


include $(LOCAL_PATH)/third_party/protobuf/Android.mk
